// AUTO-GENERATED by generate.py — DO NOT EDIT
// Source: SQL-on-FHIR v2 test suite (https://github.com/FHIR/sql-on-fhir-v2)
import ballerina/test;

json[] combinationsResources = [
    {
        "id": "pt1",
        "resourceType": "Patient"
    },
    {
        "id": "pt2",
        "resourceType": "Patient"
    },
    {
        "id": "pt3",
        "resourceType": "Patient"
    }
];


@test:Config {}
function testSelect() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "select": [
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "id",
                                "type": "id"
                            }
                        ]
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id": "pt1"
        },
        {
            "id": "pt2"
        },
        {
            "id": "pt3"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testColumnSelect() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "column_id",
                        "type": "id"
                    }
                ],
                "select": [
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "select_id",
                                "type": "id"
                            }
                        ]
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "column_id": "pt1",
            "select_id": "pt1"
        },
        {
            "column_id": "pt2",
            "select_id": "pt2"
        },
        {
            "column_id": "pt3",
            "select_id": "pt3"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testSiblingSelect() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "id_1",
                        "type": "id"
                    }
                ]
            },
            {
                "column": [
                    {
                        "path": "id",
                        "name": "id_2",
                        "type": "id"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id_1": "pt1",
            "id_2": "pt1"
        },
        {
            "id_1": "pt2",
            "id_2": "pt2"
        },
        {
            "id_1": "pt3",
            "id_2": "pt3"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testSiblingSelectInsideASelect() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "select": [
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "id_1",
                                "type": "id"
                            }
                        ]
                    },
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "id_2",
                                "type": "id"
                            }
                        ]
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id_1": "pt1",
            "id_2": "pt1"
        },
        {
            "id_1": "pt2",
            "id_2": "pt2"
        },
        {
            "id_1": "pt3",
            "id_2": "pt3"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testColumnSelectWithWhere() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "column_id",
                        "type": "id"
                    }
                ],
                "select": [
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "select_id",
                                "type": "id"
                            }
                        ]
                    }
                ]
            }
        ],
        "where": [
            {
                "path": "id = 'pt1'"
            }
        ]
    };
    json[] expected = [
        {
            "column_id": "pt1",
            "select_id": "pt1"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testUnionallForeachColumnSelect() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "select": [
                    {
                        "column": [
                            {
                                "path": "id",
                                "name": "id",
                                "type": "id"
                            }
                        ]
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id": "pt1"
        },
        {
            "id": "pt2"
        },
        {
            "id": "pt3"
        }
    ];
    json[] result = check evaluate(combinationsResources, view);
    test:assertEquals(result, expected);}
