// AUTO-GENERATED by generate.py — DO NOT EDIT
// Source: SQL-on-FHIR v2 test suite (https://github.com/FHIR/sql-on-fhir-v2)
import ballerina/test;

json[] fnReferenceKeysResources = [
    {
        "resourceType": "Patient",
        "id": "p1",
        "link": [
            {
                "other": {
                    "reference": "Patient/p1"
                }
            }
        ]
    },
    {
        "resourceType": "Patient",
        "id": "p2",
        "link": [
            {
                "other": {
                    "reference": "Patient/p3"
                }
            }
        ]
    }
];


@test:Config {}
function testGetreferencekeyResultMatchesGetresourcekeyWithoutTypeSpecifier() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "getResourceKey() = link.other.getReferenceKey()",
                        "name": "key_equal_ref",
                        "type": "boolean"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "key_equal_ref": true
        },
        {
            "key_equal_ref": false
        }
    ];
    json[] result = check evaluate(fnReferenceKeysResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testGetreferencekeyResultMatchesGetresourcekeyWithRightTypeSpecifier() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "getResourceKey() = link.other.getReferenceKey(Patient)",
                        "name": "key_equal_ref",
                        "type": "boolean"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "key_equal_ref": true
        },
        {
            "key_equal_ref": false
        }
    ];
    json[] result = check evaluate(fnReferenceKeysResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testGetreferencekeyResultMatchesGetresourcekeyWithWrongTypeSpecifier() returns error? {
    json view = {
        "resource": "Patient",
        "select": [
            {
                "column": [
                    {
                        "path": "getResourceKey() = link.other.getReferenceKey(Observation)",
                        "name": "key_equal_ref",
                        "type": "boolean"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "key_equal_ref": ()
        },
        {
            "key_equal_ref": ()
        }
    ];
    json[] result = check evaluate(fnReferenceKeysResources, view);
    test:assertEquals(result, expected);}
