// AUTO-GENERATED by generate.py — DO NOT EDIT
// Source: SQL-on-FHIR v2 test suite (https://github.com/FHIR/sql-on-fhir-v2)
import ballerina/test;

json[] validateResources = [
    {
        "resourceType": "Patient",
        "name": [
            {
                "family": "F1.1"
            }
        ],
        "id": "pt1"
    },
    {
        "resourceType": "Patient",
        "id": "pt2"
    }
];


@test:Config {}
function testEmpty() {
    json view = {};
    json[]|error result = evaluate(validateResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: empty");
}

@test:Config {}
function testMissingResource() {
    json view = {
        "select": [
            {
                "column": [
                    {
                        "name": "id",
                        "path": "id",
                        "type": "id"
                    }
                ]
            }
        ]
    };
    json[]|error result = evaluate(validateResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: missing resource");
}

@test:Config {}
function testWrongFhirpath() {
    json view = {
        "resource": "Patient",
        "status": "active",
        "select": [
            {
                "forEach": "@@"
            }
        ]
    };
    json[]|error result = evaluate(validateResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: wrong fhirpath");
}

@test:Config {}
function testWrongTypeInForeach() {
    json view = {
        "resource": "Patient",
        "status": "active",
        "select": [
            {
                "forEach": 1
            }
        ]
    };
    json[]|error result = evaluate(validateResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: wrong type in forEach");
}

@test:Config {}
function testWhereWithPathResolvingToNotBoolean() {
    json view = {
        "resource": "Patient",
        "status": "active",
        "select": [
            {
                "column": [
                    {
                        "name": "id",
                        "path": "id",
                        "type": "id"
                    }
                ]
            }
        ],
        "where": [
            {
                "path": "name.family"
            }
        ]
    };
    json[]|error result = evaluate(validateResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: where with path resolving to not boolean");
}
