// AUTO-GENERATED by generate.py — DO NOT EDIT
// Source: SQL-on-FHIR v2 test suite (https://github.com/FHIR/sql-on-fhir-v2)
import ballerina/test;

json[] viewResourceResources = [
    {
        "id": "pt1",
        "resourceType": "Patient"
    },
    {
        "id": "pt2",
        "resourceType": "Patient"
    },
    {
        "id": "ob1",
        "resourceType": "Observation",
        "code": {
            "text": "code"
        },
        "status": "final"
    }
];


@test:Config {}
function testOnlyPts() returns error? {
    json view = {
        "resource": "Patient",
        "status": "active",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "id",
                        "type": "id"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id": "pt1"
        },
        {
            "id": "pt2"
        }
    ];
    json[] result = check evaluate(viewResourceResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testOnlyObs() returns error? {
    json view = {
        "resource": "Observation",
        "status": "active",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "id",
                        "type": "id"
                    }
                ]
            }
        ]
    };
    json[] expected = [
        {
            "id": "ob1"
        }
    ];
    json[] result = check evaluate(viewResourceResources, view);
    test:assertEquals(result, expected);}

@test:Config {}
function testResourceNotSpecified() {
    json view = {
        "status": "active",
        "select": [
            {
                "column": [
                    {
                        "path": "id",
                        "name": "id",
                        "type": "id"
                    }
                ]
            }
        ]
    };
    json[]|error result = evaluate(viewResourceResources, view);
    test:assertTrue(result is error, msg = "Expected an error for: resource not specified");
}
