// AUTO-GENERATED by generate.py — DO NOT EDIT

import ballerina/sql;
import ballerinax/postgresql.driver as _;

configurable string host = "localhost";
configurable int port = 5432;
configurable string database = "postgres";
configurable string username = "postgres";
configurable string password = "postgres";

// Satisfies sql:ParameterizedQuery for a runtime SQL string with no value bindings,
// used to execute dynamically generated DDL (e.g. CREATE VIEW).
class DynamicQuery {
    *sql:ParameterizedQuery;
    public final (string[] & readonly) strings;
    public final sql:Value[] insertions = [];

    function init(string sql) {
        self.strings = [sql].cloneReadOnly();
    }
}
